Send and Receive data from the Api
Yerimah/Leaderboard-App pull request #3
Opened 2022-02-03 21:43 UTC by Yerimah

In this branch we:

- Created a new game with the name of your choice by using the API.
- Implemented the "Refresh" button.
- Implement the form "Submit" button.
- Use async and await JavaScript features to consume the API

2022-02-03 22:10 UTC, Dipeshtwis requested changes
Hi @Yerimah, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: Used `async`, `await`, and `fetch` method to send and receive data.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

**_Check the comments under the review_**

- [ ] README file should have a step to run the project locally. Currently, you have missed mentioning the command to run the project. [Hint: `npm start`]

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 22:10 UTC, Dipeshtwis commented on src/index.html
> +                    <li class="score">Gerald: 100</li> -->
- [ ] I would recommend removing the commented code to make the codebase cleaner.

2022-02-03 22:10 UTC, Dipeshtwis commented on src/index.js
> +});
- [ ] When the Refresh button is click, it should hit the GET API endpoint causing the scores list to change but in your case currently, it removing all content from the UI. Please fix that.

2022-02-04 12:38 UTC, t-yanick approved these changes
Hi @Yerimah, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-04 13:24 UTC, merged